### ISSUE TITLE
well-known URIs / configuration advertisment

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/edv-spec#12]
we use well-known URIs for this:

https://did-edv.web.app/api/docs/static/index.html#/default/get__well_known_edv_configuration

^ this is not standard or specified anywhere....

How can I discover if a server supports SDS?

**Comment by msporny** [comment]
This was discussed on the 2021-04-29 call. There were a variety of concerns raised about using /.well-known/ (such as, what happens when you want an EDV on a separate URL, discovery, etc). Suggestions were make the root URL discoverable, where /.well-known/  *could* be one of the URLs for discoverability.

It was suggested that we should have a call dedicated to this topic.

**Comment by Therecanbeonlyone1969** [comment]
Who is interested in a one (or more) topic calls on this subject, in addition to the regular TF meeting, more generally

- what are good normative requirements around **secure** discoverability?
- what implementation guidelines and recommendations should be given to implementers, e.g., best way to use .well-known?

Please, mark with a thumbs-up emoji if interested!

**Comment by agropper** [comment]
👍

**Comment by tplooker** [comment]
Discussed on the May 13th WG call, suggested next step to move this issue forward is to document use-cases for discovery

**Comment by msporny** [comment]
A point:

The current EDV spec has a solution for configuration discovery. The URL paths have a structure to them and given any EDV resource URL, you know how to get to the configuration.

and a question:

What are .well-known URI advertisements supposed to achieve? In what use case would you start there? Are we assuming that you have no access to any EDV resources?

**Comment by OR13** [comment]
does this EDV support more than X25519.... does this edv have a TOS / PP?
Other vendor specific meta data... etc...

I think the assumption is more: How can you tell who runs this service and how its configured, and what should you assume if you can't find an answer.

**Comment by tplooker** [comment]
Related to #26

**Comment by msporny** [comment]
Also related to #25.

**Comment by msporny** [comment]
We don't have a use case for .well-known URI-based discovery. We do have use cases related to discovering a configuration from an EDV endpoint URL.

I suggest we close this issue as it's already being tracked in #26 and #25.

**Comment by msporny** [comment]
There was agreement to close this issue on the 2021-06-24 call since there are no use cases that require .well-known and because we're tracking related "discoverability" issues in #26 and #25.
