### ISSUE TITLE
Is the Data Vault Configuration stored as a (plain text) Document/resource or aa an EncryptedDocument in its data vault?

### ISSUE THREAD

**Issue by mwherman2000** [decentralized-identity/edv-spec#18]
Is the Data Vault Configuration stored as a StructuredDocument (plain text document/resource) or as an EncryptedDocument in its data vault?

Reference: https://identity.foundation/confidential-storage/#datavaultconfiguration

**Comment by dmitrizagidulin** [comment]
Discussed on Jun 10, 2021 call.

Comment from @dlongley - given that all the information in the vault config is public (and is fine for the server to see), there isn't a requirement for the vault config be encrypted.

Comment from @mwherman2000 - this is ok to close.
