### ISSUE TITLE
Does the History API cover configuration changes?

### ISSUE THREAD

**Issue by msporny** [decentralized-identity/edv-spec#24]
When querying history, do we see the sequence change applied to configuration documents. Digital Bazaar's implementation does this.

Do we want a separate history API for configuration changes vs. document changes?

Tracking configuration changes have effects on how replication hand-off from "primary" to "secondary" are affected by this decision.

**Comment by msporny** [comment]
I suggest that there shouldn't be any difference between a document and a configuration, both should expose the same history API and sequence numbers should affect both of those things.

**Comment by tplooker** [comment]
A question related to this issue was discussed on the Jun 24th WG call, does the sequence number increment upon changes to the configuration document as that will effect how this integrates with history API as it is currently defined in the spec.

**Comment by dmitrizagidulin** [comment]
Discussed on Sep 2, 2021 call.

The group would want to see use cases for why we'd need this functionality.
