### ISSUE TITLE
What are the use cases for endpoint discovery?

### ISSUE THREAD

**Issue by msporny** [decentralized-identity/edv-spec#25]
We have some use cases documented that speak to discovery, but we haven't generated why someone would want to do it.

**Comment by tplooker** [comment]
Discussed on the 24th of June WG call, suggestion is to time box closing this issue over the next couple of months if no concrete use cases are suggested.

**Comment by dmitrizagidulin** [comment]
Revisited on Sep 2, 2021 call. Closing the issue since no use cases were proposed.
