### ISSUE TITLE
Content Change Detection and Tracking vs. Content Change Notification

### ISSUE THREAD

**Issue by mwherman2000** [decentralized-identity/edv-spec#29]
The current EDV CS V1 spec supports the former but not the latter.
However, the latter can be built on top of the former at the client or CS Services level.
![108412896-966c5c00-71e7-11eb-8836-1a04cbd16fb6](https://user-images.githubusercontent.com/6101736/108451843-be2de500-7224-11eb-87d9-437be6bceb3a.png)

**Comment by tplooker** [comment]
Discussed on the 24th of June WG call, since the opening of this issue the spec has added an API to expose a list of changes to documents in an EDV in a PULL style model. However this does not cover the case of notification or PUSH models.

**Comment by TallTed** [comment]
The *issue* here is unclea.  It seems you might reword title and/or initial post to say "we need a push mechanism" because ... we do.

**Comment by dmitrizagidulin** [comment]
Discussed on Sep 2, 2021 call.

@mwherman2000 - Can you add further clarification to this? It's unclear on what the ask is.
Adding a 'Pending Close - 14 days' tag.

**Comment by dmitrizagidulin** [comment]
Closing, please feel free to open further issues with questions or clarification.
