### ISSUE TITLE
Feature request: Batch document requests

### ISSUE THREAD

**Issue by DRK3** [decentralized-identity/edv-spec#40]
Hi (again!),

Another useful feature that many databases have is the ability to upsert multiple documents at once, or delete multiple documents at once ~~(or read multiple documents at once)~~. Having this in EDV would be useful as well.

Edit: Removed the suggestion to read documents at once, as I realized right after I wrote it that it wouldn't really work easily with the current scheme whereby the document ID forms part of the URL...

**Comment by dmitrizagidulin** [comment]
Being addressed by PR https://github.com/decentralized-identity/edv-spec/pull/16

**Comment by DRK3** [comment]
Completed in #16
