### ISSUE TITLE
Feature request: Ability to return full documents in query instead of only document locations

### ISSUE THREAD

**Issue by DRK3** [decentralized-identity/edv-spec#43]
Hi,

In Aries-Framework-Go we have an [EDV REST provider](https://github.com/hyperledger/aries-framework-go/blob/master/pkg/storage/edv/restprovider.go) which is used alongside an "[EncryptedFormatter](https://github.com/hyperledger/aries-framework-go/blob/master/pkg/storage/edv/encryptedformatter.go)" in order to allow us to translate between (k,v) pairs and encrypted documents in a way that allows it to conform to the storage interface there. 

Currently the spec only allows document locations to be returned and not the full documents themselves. This results in us having to make two REST calls per `Get` operation, which was so expensive that I actually [implemented an optional "extension" to our TrustBloc EDV implementation](https://github.com/trustbloc/edv/pull/162) in order to support returning full documents on a query. Right now I'm in the process of adding this optional capability to the Aries-Framework-Go EDV REST provider.

It would be very beneficial for our use case (and probably others) if the spec could support the ability to return full documents in query results.

Thanks! Let me know if you have any questions.

**Comment by dmitrizagidulin** [comment]
Addressed by PR https://github.com/decentralized-identity/edv-spec/pull/13, closing.
