### ISSUE TITLE
Clarification on the inception of a new document's ID

### ISSUE THREAD

**Issue by llorllale** [decentralized-identity/edv-spec#47]
We have implemented an [encrypted data vault](https://github.com/trustbloc/edv) and we are now moving to integrate an EDV client for it as a "storage plugin" to [aries-framework-go](https://github.com/hyperledger/aries-framework-go).

One of the sticking points is the ambiguity in the spec w.r.t. a new document's identifier.

To create a new document one must `POST` a request with an EncryptedDocument structure. This structure has an `id` property that the client assigns a value to. Inception of this ID is on the client side.

[This example response](https://identity.foundation/secure-data-store/#example-10-successful-data-vault-document-creation-response) is returning a different ID than the one sent in the example request right above it.

**Request**

* Clarification on where the spec or the group's thinking is headed in, whether the identifier is controlled by the client or controlled by the server, and
* Add normative text to the spec that clarifies this point

**Comment by DRK3** [comment]
For us, we no longer need the ability to do range queries based on key/ID names with a prefix. We now use encrypted indexes to solve the same problem. I believe this can be closed, unless there are any further concerns.

**Comment by DRK3** [comment]
Clarification: "we" in my previous comment referring to @llorllale and I (I was working with him in that area)
