### ISSUE TITLE
Should Document / Resource IDs be URIs?

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/edv-spec#52]
Related: https://github.com/decentralized-identity/secure-data-store/issues/77

I would be very much in favor of saying... we are gonna use URIs for identifiers.

**Comment by dmitrizagidulin** [comment]
Discussed on Aug 5, 2021 

- Group agrees to use Resources as a general umbrella term for Documents/Streams.
- Requiring traditional https URLs has downsides/implications for replication (does an ID bind to a resource's domain/location)
- The recommendation is to only use a persistent / non-binding URI for documents, that remains stable through replication.

**Comment by TallTed** [comment]
> Should Document / Resource IDs be URIs?

URIs, yes.

HTTP/S URIs, maybe, maybe not.

w3id-(or similar service)-based HTTP/S URIs would be fine, as would DID URLs, to preserve the URIs as identifiers while allowing resource relocation, service provider changes, etc.  Any such strategy would need attention to privacy preservation and the like, which details would vary with the specifics of the chosen URIs and their resolution.

**Comment by dmitrizagidulin** [comment]
Discussed on the Sep 2, 2021 call.

Clarification: one reason to have separate Resource URIs _and_ Resource IDs is to enable the portability mechanism.
Which leads to the question -- what is our strategy for portability?
Specifically, if I have an authorization for an encrypted document in one vault, and the document is replicated to another vault, how does one make sure that my authorization works on that second vault? Opening a separate issue for that...
