### ISSUE TITLE
Explanation for the "equals" syntax in encrypted index query example

### ISSUE THREAD

**Issue by DRK3** [decentralized-identity/edv-spec#56]
Hi,

[Example 32](https://digitalbazaar.github.io/encrypted-data-vaults/#example-32-data-vault-query-for-a-specifically-indexed-value) in the EDV spec shows the following example query:

`{
  "index": "DUQaxPtSLtd8L3WBAIkJ4DiVJeqoF6bdnhR7lSaPloZ",
  "equals": [
    {"QV58Va4904K-18_L5g_vfARXRWEB00knFSGPpukUBro":
      "dh327d234h8437hc34f43f43ZXGHDXG"}
  ]
}`

It's not clear to me what the meaning of the `equals` field value is. It looks like an array - is this for specifying a "equals this or this or this..." type of query? What is the relationship between `QV58Va4904K-18_L5g_vfARXRWEB00knFSGPpukUBro` and `dh327d234h8437hc34f43f43ZXGHDXG`? An explanation in the spec could make it more helpful for implementers.

Thanks!

**Comment by DRK3** [comment]
I'm working on a PR for this, but I think I need some more information first.

Right now, the encrypted index info in an Encrypted Document looks like this (this was taken from the spec):

```
"indexed": [{
      "sequence": 0,
      "hmac": {
        "id": "https://example.com/kms/z7BgF536GaR",
        "type": "Sha256HmacKey2019"
      },
      "attributes": [{
        "name": "CUQaxPtSLtd8L3WBAIkJ4DiVJeqoF6bdnhR7lSaPloZ",
        "value": "RV58Va4904K-18_L5g_vfARXRWEB00knFSGPpukUBro",
        "unique": true
      }, {
        "name": "DUQaxPtSLtd8L3WBAIkJ4DiVJeqoF6bdnhR7lSaPloZ",
        "value": "QV58Va4904K-18_L5g_vfARXRWEB00knFSGPpukUBro"
      }]
    }],
```

and the example of a query (not using the "has" keyword) looks like this:
```
  {
    "index": "DUQaxPtSLtd8L3WBAIkJ4DiVJeqoF6bdnhR7lSaPloZ",
    "equals": [
      {"QV58Va4904K-18_L5g_vfARXRWEB00knFSGPpukUBro":
        "dh327d234h8437hc34f43f43ZXGHDXG"}
    ],
    "returnFullDocuments": false
  }
```

It looks to me like encrypted index attributes have just two properties: a `name` and a `value`, and it looks like "index" in the query corresponds to `name`. `equals` seems to correspond with `value`... except that this `equals` is a key-value pair, and `value` in an Encrypted Document is just a single value. I was re-reading @dlongley's post about the `equals` filter, but I'm not quite sure how to apply it to the examples I applied above (e.g. - where would `dh327d234h8437hc34f43f43ZXGHDXG` from the above example fit in fit in? Where would it be in the Encrypted Document?).

I'd like to propose a query syntax that's essentially what @dlongley posted, but tweaked slightly to fit the current data model in the spec better. I'd also like to suggest renaming the `index` field in the query to `name` so that it matches the Encrypted Document model.

I just wanted to see if anyone had any thoughts about this before I make a PR (@msporny @dmitrizagidulin?). (Although, it might be easier to understand my proposal if I just create the PR - so you can also let me know if you think I should just do that first)

**Comment by dlongley** [comment]
I think the example is probably just wrong due to copy/paste errors?

It seems to me that it should have been:

```js
  {
    "index": "DUQaxPtSLtd8L3WBAIkJ4DiVJeqoF6bdnhR7lSaPloZ",
    "equals": [
      {"DUQaxPtSLtd8L3WBAIkJ4DiVJeqoF6bdnhR7lSaPloZ":
        "QV58Va4904K-18_L5g_vfARXRWEB00knFSGPpukUBro"}
    ],
    "returnFullDocuments": false
  }
```

If the intention was to show a query looking for documents matching the second attribute. The keys in the `equals` map being the names of the attributes and the values being the attribute values.

**Comment by DRK3** [comment]
@dlongley That makes more sense to me.

One question, though - why does the client need to specify the ID of the HMAC key?

**Comment by dmitrizagidulin** [comment]
@DRK3 - I think that's for if you're using a KMS system. (it can only do stuff by key id)

**Comment by dlongley** [comment]
@DRK3,

The ID of the HMAC key doubles as the ID for the index since they are all HMAC based. We could have another identifier for the index but it seems like it would just be another piece of information to get out of sync. If you were to decouple it from the HMAC key the whole index would need to be recomputed anyway should the key change (for example). So this should be totally unrelated to the use (or not) of a KMS.
